import { CorrectNews } from './correctNews/index';
export {Main} from './main'
// export {New} from './new'
export {Sport} from './sport'
// export {Investigations} from './investigations'
// export {Weather} from './weather'
// export {Business} from './business'
// export {Technology} from './technology'
export {Metainfo} from './metainfo'
export {CorrectNews} from './correctNews'
export {Admin} from './admin'
export {CreatePage} from './create'
